.gitignore, analysis.py, snakes.py
have a separate class to reconstruct and get the morphological snakes
=> Code cleanup

analysis.py, clusterTools.py, snakes.py
- cluster shapes are computed as lateral / longitudinal widths rotating the cluster along the major / minor axes.
=> Clustering with DBSCAN and analysis of the cluster shapes

analysis.py, clusterTools.py, snakes.py
- Do the clustering with larger rebinning, but then calculate profiles on the full resolution image.
- Some improvements, even if no optimization of the code is done
=> Add the full resolution cluster properties

analysis.py, cameraChannel.py, clusterTools.py, snakes.py
major thing is the speedup of the code for the fullresolution cluster plotting and the fixes for the fullres binning
=> Bugfixes and improvements in profiles with fullres

analysis.py, snakes.py
It works, apart that I had to switch off the pyplot when running with multiprocess
on MacOS High Sierra. It could be a problem of Apple python, but since it is not strictly
necessary, that plotting is off in analysis.py
=> Implement multiprocess

analysis.py, pmtSignal.py
needed when removing max-events option
=> Small fix for multiprocess

analysis.py, clusterTools.py, rootlogon.C, snakes.py, treeVars.py, utilities.py, waveform.py
- now margins are calculated along the cluster axes
- cluster shapes are calculated on the full reso cluster and put in the ntuple
=> Refinement of the cluster margins in full resolution and Cluster shapes calculation

analysis.py, cameraChannel.py, clusterTools.py, snakes.py, treeVars.py, waveform.py
- Fix the zero suppression before clustering
- Add cluster filtering on cluster shapes
- Tuning of the cluster shape calculation
- New variables added to the reconstruction
- Cleanup of the code
=> major tuning, cluster selection, cleanup

analysis.py, cameraChannel.py, clusterTools.py, snakes.py, utilities.py
N.B. There are few lines to be uncommented and fixed to run on BTF (in snakes.py and analysis.py)
=> Major updates for BTF analysis

plotter/correlations.py, plotter/fng/plots.txt, plotter/light_yield.py, plotter/plotFile.py, plotter/recoPlots.py
Not yet refined, but basic functionality working
=> Plotting tools

reconstruction.py, snakes.py
Makes outfile_chunkN.root for N chunks, to be hadded at the end
=> implement multithreading for tree filling also

clusterTools.py, plotter/fng/plots.txt, plotter/recoPlots.py, reconstruction.py
use the cluster in full resolution to save nhits, integrals, etc.
=> Fix for track properties

plotter/fng/plots.txt
just to test a fork
@igorabritta
=> Stupid update

clusterTools.py
=> Cosmetics on 2D cluster plots

configFile.txt, debug_code/tools_lib.py, snakes.py
1. add the cut on the neighbor average in the config file, 
2. remove duplication in DEBUG mode, 
3. loosen the zero-suppression cut and the neighboring pixels
=> Few minor changes

configFile.txt, reconstruction.py, waveform.py
some debug in the ToT calculation + some tuning of the peak finder + the rebinned waveform is the sum of the bins, not the average.
=> Resume PMT reconstruction

configFile.txt, reconstruction.py, waveform.py
=> This is the PMT pull-request, but on the right branch

configFile.txt, reconstruction.py, swiftlib.py
=> Automatic root file from swift

clusterTools.py, treeVars.py
=> Implement Gaussian fit on profiles

plotter/fitter/density_fitter.py, plotter/fitter/libCpp/histFitter.C, plotter/fitter/libPython/classUtils.py, plotter/fitter/libPython/fitUtils.py, snakes.py
used to get the efficiency on AmBe recoils
=> Add a simple template fitter

clusterTools.py, snakes.py, supercluster.py, waveform.py
Improve also the plotting of the profiles with the peak finder. First step to understand the cluster shape.
=> Fix the peak finding along the cluster profiles

plotter/simple_plot.py
ROC curve are done on background-subtracted AmBe and Fe55 distributions.
Still missing error bands on this.
=> plot 3 components and simple ROC curves

clusterTools.py, configFile.txt, plotter/simple_plot.py, snakes.py, supercluster.py, waveform.py
- fix the configFile.txt for py3
- plotting stuff added
=> Fix the default config file for python3 + plotting

modules_config/energyCalibrator.txt
=> config file for the energy calibrator missing

modules_config/energyCalibrator.txt
=> config file for the energy calibrator

energyCalibrator.py
bugfix: the indices of points of the slices cannot be negative !
=> check if the indices of the points in circle are positive

configFile.txt, configFileNeutrons7030.txt, plotter/simple_plot.py, snakes.py
- this is for debugging purposes.
- few other plotting stuff for offline analysis.
=> Add the possibility to plot the 2D pictures with superclusters only

plotter/simple_plot.py
Add the average calibration and the full neutrons selection. Plus the selection for the 60 keV photons
=> offline analysis stuff only 

plotter/simple_plot.py
Plotting of:
- cluster direction
- cluster asymmetry along the profile
=> Offline analysis stuff

plotter/simple_plot.py
Porting mainly the profile coordinates in the tree in #91
=> Align master with dev branch

cameraChannel.py, configFile.txt, reconstruction.py, swiftlib.py
Hi Emanuele,
I started from scratch, I am sorry for the last one, I was not sure how git repository works at all.
Now should be good.
Let me know if there is something that need to be changed.
Thank you,
Karolina
=> pix-by- pix correction

debug_code/plot_pickled_image.py, plotter/ambe_miscellanea.py, plotter/simple_plot.py
=> Some plotting stuff

cameraChannel.py, clusterTools.py, plotter/ambe_miscellanea.py, snakes.py
Mostly for plots of LEMON-20-001 paper. No algorithm changes.
=> Move to real length for plots and miscellanea updates

plotter/simple_plot.py
Only offline analysis code related.
=> paper changes

cameraChannel.py, clusterTools.py, configFileNeutrons7030.txt, modules_config/geometry_lemon.txt, modules_config/geometry_lime.txt, reconstruction.py, snakes.py, supercluster.py, swiftlib.py
can be switched from the parameter: "geometry" in the config file.
For the moment only "lemon" and "lime" are implemented. It loads configurations files: modules_config/geometry_lemon.txt  or modules_config/geometry_lime.txt
=> Preparation for LIME: Geometry taken from configuration

configFileNeutrons7030.txt, debug_code/tools_lib.py, reconstruction.py, snakes.py
N.B. Finally the images created in debug mode and x and y correspond to the naive expectation (y axis = vertical)
@davidepinci @gmazzitelli @igorabritta
=> first running version of LIME reconstruction

reconstruction.py, supercluster.py, swiftlib.py
Up to run 3805 in swiftlib: https://github.com/CYGNUS-RD/reconstruction/commit/59475f29eb60ba019e04fdc5286f14c4edd0dfea
@gmazzitelli
=> Updates to re-automatize the running on the cloud for the LIME runs

scripts/activate_cygno_lngs.sh, scripts/submit_batch.py
some scripts to submit to the PBS batch system in LNGS 
@igorabritta @gmazzitelli
=> submit to LNGS batch

plotter/ambe_miscellanea.py, plotter/simple_plot.py
Only for the offline analysis of the AmBe data with LIME.
=> updates for first AmBe LIME analysis

reconstruction.py
it was easier than expected (once known...)
@baracch @gmazzitelli 
It seems not to hang the multiprocess at LNGS interactively. Now launched an extended test on the batch queues.
=> Solve the non closure of multithread at LNGS

scripts/submit_batch.py
add "-q" <queue> option. 
Default is still "cygno-custom", because it has larger number of cores and memory. But resources are limited. 
If one uses "-q cygno", it will submit to the standard queue dedicated to CYGNO, where more jobs should run, but:
1. it cannot mount the /mnt/ssdcache to store the input (it will automatically use /tmp/$USER), so it will be a bit slower to read, not a problem at all - the time is CPU-dominated
2. max number of threads is 8 and max RAM is 9GB. The submission script thresholds this automatically
So to recap:
---> `<script> -q cygno-custom` (or without the option, since it is the default)  
sends the jobs with 24 core / 30GB RAM. Faster, but only if the queue is free. It's your subaru impreza
---> `<script> -q cygno`
sends the jobs with 8 cores / 8 GB RAM. …
=> Add the possibility to run on standard "cygno" batch queue @ LNGS

reconstruction.py
By mistake in #132 left on the production of 2 profiles / cluster / event when not in debug mode...
=> Avoid producing profile PDF files / event in normal mode... 
